//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Admin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Admin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Admin", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        internal static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category {0} was successfully created..
        /// </summary>
        internal static string CategoryCreatedText {
            get {
                return ResourceManager.GetString("CategoryCreatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category sucessfully created.
        /// </summary>
        internal static string CategoryCreatedTitle {
            get {
                return ResourceManager.GetString("CategoryCreatedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Forum.
        /// </summary>
        internal static string CreateForum {
            get {
                return ResourceManager.GetString("CreateForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Photo Category.
        /// </summary>
        internal static string CreatePhotoCategory {
            get {
                return ResourceManager.GetString("CreatePhotoCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User.
        /// </summary>
        internal static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Video Category.
        /// </summary>
        internal static string CreateVideoCategory {
            get {
                return ResourceManager.GetString("CreateVideoCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Forums.
        /// </summary>
        internal static string ManageForums {
            get {
                return ResourceManager.GetString("ManageForums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The User {0}  was successfully created..
        /// </summary>
        internal static string UserCreatedText {
            get {
                return ResourceManager.GetString("UserCreatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User successfully created.
        /// </summary>
        internal static string UserCreatedTitle {
            get {
                return ResourceManager.GetString("UserCreatedTitle", resourceCulture);
            }
        }
    }
}
