//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mail() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Mail", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} uploaded new photos in the album &apos;{1}&apos;.
        /// </summary>
        internal static string NewPhotosBody {
            get {
                return ResourceManager.GetString("NewPhotosBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New photos on .
        /// </summary>
        internal static string NewPhotosTitle {
            get {
                return ResourceManager.GetString("NewPhotosTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} replied to the topic &apos;{1}&apos; on {2}.
        /// </summary>
        internal static string NewPostBody {
            get {
                return ResourceManager.GetString("NewPostBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New post on .
        /// </summary>
        internal static string NewPostTitle {
            get {
                return ResourceManager.GetString("NewPostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} created the topic &apos;{1}&apos; on {2}.
        /// </summary>
        internal static string NewTopicBody {
            get {
                return ResourceManager.GetString("NewTopicBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New topic on .
        /// </summary>
        internal static string NewTopicTitle {
            get {
                return ResourceManager.GetString("NewTopicTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} uploaded the video &apos;{1}&apos; on {2}.
        /// </summary>
        internal static string NewVideoBody {
            get {
                return ResourceManager.GetString("NewVideoBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New video on .
        /// </summary>
        internal static string NewVideoTitle {
            get {
                return ResourceManager.GetString("NewVideoTitle", resourceCulture);
            }
        }
    }
}
